<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<PackageId>CSharpScripts</PackageId>
		<AssemblyName>tools</AssemblyName>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
	</PropertyGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="CSharpScripts.Tests"/>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AngleSharp" Version="*"/>
		<PackageReference Include="CsvHelper" Version="*"/>
		<PackageReference Include="Google.Apis" Version="*"/>
		<PackageReference Include="Google.Apis.Auth" Version="*"/>
		<PackageReference Include="Google.Apis.YouTube.v3" Version="*"/>
		<PackageReference Include="Hqub.Last.fm" Version="*"/>
		<PackageReference Include="MetaBrainz.MusicBrainz" Version="*"/>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="*"/>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="*"/>
		<PackageReference Include="Microsoft.Playwright" Version="*"/>
		<PackageReference Include="NTextCat" Version="*"/>
		<PackageReference Include="Npgsql" Version="*"/>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="*"/>
		<PackageReference Include="ParkSquare.Discogs" Version="*"/>
		<PackageReference Include="PdfPig" Version="*"/>
		<PackageReference Include="Polly" Version="*"/>
		<PackageReference Include="Polly.RateLimiting" Version="8.6.5"/>
		<PackageReference Include="RestSharp" Version="*"/>
		<PackageReference Include="Riok.Mapperly" Version="*"/>
		<PackageReference Include="Serilog" Version="*"/>
		<PackageReference Include="Serilog.Enrichers.Process" Version="*"/>
		<PackageReference Include="Serilog.Enrichers.Thread" Version="*"/>
		<PackageReference Include="Serilog.Formatting.Compact" Version="*"/>
		<PackageReference Include="Serilog.Sinks.File" Version="*"/>
		<PackageReference Include="SmartReader" Version="*"/>
		<PackageReference Include="Spectre.Console" Version="*"/>
		<PackageReference Include="Spectre.Console.Cli" Version="*"/>
		<PackageReference Include="System.Threading.RateLimiting" Version="*"/>
	</ItemGroup>
	<Target Name="CopyNTextCatProfile" AfterTargets="Build">
		<ItemGroup>
			<NTextCatFiles Include="$(NuGetPackageRoot)ntextcat\**\content\*.xml"/>
		</ItemGroup>
		<Copy
			SourceFiles="@(NTextCatFiles)"
			DestinationFolder="$(OutputPath)"
			SkipUnchangedFiles="true"
		/>
	</Target>
</Project>
