<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<PackageId>CSharpScripts</PackageId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="*" />
		<PackageReference Include="Google.Apis" Version="*" />
		<PackageReference Include="Google.Apis.Auth" Version="*" />
		<PackageReference Include="Google.Apis.Drive.v3" Version="*" />
		<PackageReference Include="Google.Apis.Sheets.v4" Version="*" />
		<PackageReference Include="Google.Apis.YouTube.v3" Version="*" />
		<PackageReference Include="Hqub.Last.fm" Version="*" />
		<PackageReference Include="MetaBrainz.MusicBrainz" Version="*" />
		<PackageReference Include="ParkSquare.Discogs" Version="*" />
		<PackageReference Include="Polly" Version="*" />
		<PackageReference Include="RestSharp" Version="*" />
		<PackageReference Include="Spectre.Console" Version="*-*" />
		<PackageReference Include="Spectre.Console.Cli" Version="*" />
	</ItemGroup>
</Project>
