<Project>
	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<TargetFramework>net11.0</TargetFramework>
		<SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<AnalysisModeStyle>Recommended</AnalysisModeStyle>
	</PropertyGroup>
</Project>
