global using System.Collections.Frozen;
global using System.ComponentModel;
global using System.Diagnostics;
global using static System.Environment;
global using System.Globalization;
global using static System.IO.Directory;
global using static System.IO.File;
global using static System.IO.Path;
global using System.Net.Sockets;
global using static System.String;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Xml;
global using CsvHelper;
global using CsvHelper.Configuration;
global using Polly;
global using Polly.Retry;
global using RestSharp;
global using Spectre.Console;
global using Spectre.Console.Cli;
global using Spectre.Console.Rendering;
global using SpectreColor = Spectre.Console.Color;
global using SpectreProgress = Spectre.Console.Progress;
global using SpectreTable = Spectre.Console.Table;
