services:
    postgres:
        image: postgres:18
        container_name: postgres
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-pg_db}
            POSTGRES_USER: ${POSTGRES_USER:-lance}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lance}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql
        restart: unless-stopped
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-lance} -d ${POSTGRES_DB:-pg_db}" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
        driver: local
