version: '3.8'

services:
    db:
        image: postgres:16
        container_name: personal_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: personal
        ports:
            - "5432:5432"
        volumes:
            - ./state/postgres-data:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
