// <auto-generated />
using System;
using System.Reflection;
using System.Text.Json;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scripts.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyCompiledModels
{
    [EntityFrameworkInternal]
    public partial class FiberyEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Scripts.Data.Entities.FiberyEntity",
                typeof(FiberyEntity),
                baseEntityType,
                propertyCount: 4,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(FiberyEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FiberyEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:DefaultValueSql", "gen_random_uuid()");

            var entityType = runtimeEntityType.AddProperty(
                "EntityType",
                typeof(string),
                propertyInfo: typeof(FiberyEntity).GetProperty("EntityType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FiberyEntity).GetField("<EntityType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            entityType.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            entityType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            entityType.AddAnnotation("Relational:ColumnType", "varchar(100)");

            var fiberyId = runtimeEntityType.AddProperty(
                "FiberyId",
                typeof(string),
                propertyInfo: typeof(FiberyEntity).GetProperty("FiberyId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FiberyEntity).GetField("<FiberyId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            fiberyId.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            fiberyId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            fiberyId.AddAnnotation("Relational:ColumnType", "varchar(255)");

            var rawData = runtimeEntityType.AddProperty(
                "RawData",
                typeof(JsonDocument),
                propertyInfo: typeof(FiberyEntity).GetProperty("RawData", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FiberyEntity).GetField("<RawData>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            rawData.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            rawData.AddAnnotation("Relational:ColumnType", "jsonb");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { entityType });
            index.AddAnnotation("Relational:Name", "idx_fibery_entities_entity_type");

            var index0 = runtimeEntityType.AddIndex(
                new[] { fiberyId, entityType },
                unique: true);
            index0.AddAnnotation("Relational:Name", "idx_fibery_entities_fibery_id_type");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "fibery");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "fibery_entities");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
