// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scripts.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyCompiledModels
{
    [EntityFrameworkInternal]
    public partial class PlaylistEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Scripts.Data.Entities.Playlist",
                typeof(Playlist),
                baseEntityType,
                propertyCount: 7,
                navigationCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Playlist).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Playlist).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var channelName = runtimeEntityType.AddProperty(
                "ChannelName",
                typeof(string),
                propertyInfo: typeof(Playlist).GetProperty("ChannelName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Playlist).GetField("<ChannelName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            channelName.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            channelName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var channelNameLower = runtimeEntityType.AddProperty(
                "ChannelNameLower",
                typeof(string),
                propertyInfo: typeof(Playlist).GetProperty("ChannelNameLower", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Playlist).GetField("<ChannelNameLower>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            channelNameLower.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            channelNameLower.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(Playlist).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Playlist).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            description.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            description.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var playlistId = runtimeEntityType.AddProperty(
                "PlaylistId",
                typeof(string),
                propertyInfo: typeof(Playlist).GetProperty("PlaylistId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Playlist).GetField("<PlaylistId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            playlistId.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            playlistId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var title = runtimeEntityType.AddProperty(
                "Title",
                typeof(string),
                propertyInfo: typeof(Playlist).GetProperty("Title", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Playlist).GetField("<Title>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            title.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            title.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var titleLower = runtimeEntityType.AddProperty(
                "TitleLower",
                typeof(string),
                propertyInfo: typeof(Playlist).GetProperty("TitleLower", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Playlist).GetField("<TitleLower>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            titleLower.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            titleLower.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { playlistId },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "youtube");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "playlists");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
