// <auto-generated />
using System;
using System.Reflection;
using System.Text.Json;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scripts.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyCompiledModels
{
    [EntityFrameworkInternal]
    public partial class ReleaseProgressEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Scripts.Data.Entities.ReleaseProgress",
                typeof(ReleaseProgress),
                baseEntityType,
                propertyCount: 16,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(ReleaseProgress).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var artist = runtimeEntityType.AddProperty(
                "Artist",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("Artist", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<Artist>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            artist.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            artist.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var composer = runtimeEntityType.AddProperty(
                "Composer",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("Composer", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<Composer>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            composer.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            composer.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var conductor = runtimeEntityType.AddProperty(
                "Conductor",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("Conductor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<Conductor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            conductor.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            conductor.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ReleaseProgress).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAt.AddAnnotation("Relational:ColumnType", "timestamptz");
            createdAt.AddAnnotation("Relational:DefaultValueSql", "CURRENT_TIMESTAMP");

            var discNumber = runtimeEntityType.AddProperty(
                "DiscNumber",
                typeof(int),
                propertyInfo: typeof(ReleaseProgress).GetProperty("DiscNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<DiscNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            discNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var duration = runtimeEntityType.AddProperty(
                "Duration",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("Duration", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<Duration>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            duration.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            duration.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var orchestra = runtimeEntityType.AddProperty(
                "Orchestra",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("Orchestra", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<Orchestra>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            orchestra.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            orchestra.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var recordingId = runtimeEntityType.AddProperty(
                "RecordingId",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("RecordingId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<RecordingId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            recordingId.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            recordingId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var recordingVenue = runtimeEntityType.AddProperty(
                "RecordingVenue",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("RecordingVenue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<RecordingVenue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            recordingVenue.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            recordingVenue.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var recordingYear = runtimeEntityType.AddProperty(
                "RecordingYear",
                typeof(int?),
                propertyInfo: typeof(ReleaseProgress).GetProperty("RecordingYear", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<RecordingYear>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            recordingYear.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var releaseId = runtimeEntityType.AddProperty(
                "ReleaseId",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("ReleaseId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<ReleaseId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            releaseId.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            releaseId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            releaseId.AddAnnotation("Relational:ColumnType", "text");

            var soloists = runtimeEntityType.AddProperty(
                "Soloists",
                typeof(JsonDocument),
                propertyInfo: typeof(ReleaseProgress).GetProperty("Soloists", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<Soloists>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            soloists.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            soloists.AddAnnotation("Relational:ColumnType", "jsonb");

            var title = runtimeEntityType.AddProperty(
                "Title",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("Title", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<Title>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            title.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            title.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var trackNumber = runtimeEntityType.AddProperty(
                "TrackNumber",
                typeof(int),
                propertyInfo: typeof(ReleaseProgress).GetProperty("TrackNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<TrackNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            trackNumber.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var workName = runtimeEntityType.AddProperty(
                "WorkName",
                typeof(string),
                propertyInfo: typeof(ReleaseProgress).GetProperty("WorkName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReleaseProgress).GetField("<WorkName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            workName.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            workName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { createdAt });
            index.AddAnnotation("Relational:Name", "idx_release_progress_created_at");

            var index0 = runtimeEntityType.AddIndex(
                new[] { releaseId });
            index0.AddAnnotation("Relational:Name", "idx_release_progress_release_id");

            var index1 = runtimeEntityType.AddIndex(
                new[] { releaseId, discNumber, trackNumber },
                unique: true);
            index1.AddAnnotation("Relational:Name", "idx_release_progress_track");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "music");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "release_progress");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
