// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyCompiledModels
{
    public partial class ScriptsDbContextModel
    {
        private ScriptsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("f186e86a-470c-4192-8265-80e7261c825c"), entityTypeCount: 10)
        {
        }

        partial void Initialize()
        {
            var album = AlbumEntityType.Create(this);
            var artist = ArtistEntityType.Create(this);
            var fiberyEntity = FiberyEntityEntityType.Create(this);
            var playlist = PlaylistEntityType.Create(this);
            var playlistVideo = PlaylistVideoEntityType.Create(this);
            var releaseProgress = ReleaseProgressEntityType.Create(this);
            var scrobble = ScrobbleEntityType.Create(this);
            var sourceRecord = SourceRecordEntityType.Create(this);
            var track = TrackEntityType.Create(this);
            var video = VideoEntityType.Create(this);

            AlbumEntityType.CreateForeignKey1(album, artist);
            PlaylistVideoEntityType.CreateForeignKey1(playlistVideo, playlist);
            PlaylistVideoEntityType.CreateForeignKey2(playlistVideo, video);
            ScrobbleEntityType.CreateForeignKey1(scrobble, track);
            TrackEntityType.CreateForeignKey1(track, album);
            TrackEntityType.CreateForeignKey2(track, artist);

            AlbumEntityType.CreateAnnotations(album);
            ArtistEntityType.CreateAnnotations(artist);
            FiberyEntityEntityType.CreateAnnotations(fiberyEntity);
            PlaylistEntityType.CreateAnnotations(playlist);
            PlaylistVideoEntityType.CreateAnnotations(playlistVideo);
            ReleaseProgressEntityType.CreateAnnotations(releaseProgress);
            ScrobbleEntityType.CreateAnnotations(scrobble);
            SourceRecordEntityType.CreateAnnotations(sourceRecord);
            TrackEntityType.CreateAnnotations(track);
            VideoEntityType.CreateAnnotations(video);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
