// <auto-generated />
using System;
using System.Reflection;
using System.Text.Json;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scripts.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyCompiledModels
{
    [EntityFrameworkInternal]
    public partial class VideoEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Scripts.Data.Entities.Video",
                typeof(Video),
                baseEntityType,
                propertyCount: 13,
                navigationCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Video).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var channelName = runtimeEntityType.AddProperty(
                "ChannelName",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("ChannelName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<ChannelName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            channelName.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            channelName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var channelNameLower = runtimeEntityType.AddProperty(
                "ChannelNameLower",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("ChannelNameLower", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<ChannelNameLower>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            channelNameLower.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            channelNameLower.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            description.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            description.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var metadata = runtimeEntityType.AddProperty(
                "Metadata",
                typeof(JsonDocument),
                propertyInfo: typeof(Video).GetProperty("Metadata", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<Metadata>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            metadata.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            metadata.AddAnnotation("Relational:ColumnType", "jsonb");

            var syncedAt = runtimeEntityType.AddProperty(
                "SyncedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(Video).GetProperty("SyncedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<SyncedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            syncedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var title = runtimeEntityType.AddProperty(
                "Title",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("Title", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<Title>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            title.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            title.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var titleLower = runtimeEntityType.AddProperty(
                "TitleLower",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("TitleLower", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<TitleLower>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            titleLower.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            titleLower.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var translatedDescription = runtimeEntityType.AddProperty(
                "TranslatedDescription",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("TranslatedDescription", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<TranslatedDescription>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            translatedDescription.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            translatedDescription.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var translatedTitle = runtimeEntityType.AddProperty(
                "TranslatedTitle",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("TranslatedTitle", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<TranslatedTitle>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            translatedTitle.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            translatedTitle.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var uploadDate = runtimeEntityType.AddProperty(
                "UploadDate",
                typeof(DateOnly?),
                propertyInfo: typeof(Video).GetProperty("UploadDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<UploadDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            uploadDate.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var url = runtimeEntityType.AddProperty(
                "Url",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("Url", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<Url>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            url.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            url.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var videoId = runtimeEntityType.AddProperty(
                "VideoId",
                typeof(string),
                propertyInfo: typeof(Video).GetProperty("VideoId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Video).GetField("<VideoId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            videoId.SetComparer(new ValueComparer<string>(
                bool (string l, string r) => string.Equals(l, r, StringComparison.Ordinal),
                int (string v) => (v == null ? 0 : StringComparer.Ordinal.GetHashCode(v)),
                string (string v) => v));
            videoId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { videoId },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "youtube");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "videos");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
