global using System.Collections.Frozen;
global using System.Diagnostics;
global using static System.Environment;
global using static System.IO.Directory;
global using static System.IO.File;
global using static System.IO.Path;
global using static System.String;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Xml;
global using CSharpScripts.Infrastructure;
global using CSharpScripts.Models;
global using CSharpScripts.Orchestrators;
global using CSharpScripts.Services.Mail;
global using CSharpScripts.Services.Music;
global using CSharpScripts.Services.Sync.Google;
global using CSharpScripts.Services.Sync.LastFm;
global using CSharpScripts.Services.Sync.YouTube;
global using Google.Apis.Auth.OAuth2;
global using Google.Apis.Drive.v3;
global using Google.Apis.Services;
global using Google.Apis.Sheets.v4;
global using Google.Apis.Sheets.v4.Data;
global using Google.Apis.YouTube.v3;
global using Google.Apis.YouTube.v3.Data;
global using Hqub.Lastfm;
global using Hqub.Lastfm.Entities;
global using Polly;
global using Polly.Retry;
global using Spectre.Console;
global using Console = CSharpScripts.Infrastructure.Console;
global using Scrobble = CSharpScripts.Services.Sync.LastFm.Scrobble;
global using YouTubeService = CSharpScripts.Services.Sync.YouTube.YouTubeService;
