global using System.Collections.Frozen;
global using System.Diagnostics;
global using static System.Environment;
global using System.Globalization;
global using static System.String;
global using static System.StringComparison;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using CSharpScripts.Core;
global using CSharpScripts.Core.Auth;
global using CSharpScripts.Data;
global using CSharpScripts.Models;
global using CSharpScripts.Services.Language;
global using CsvHelper;
global using CsvHelper.Configuration;
global using MetaBrainz.MusicBrainz.Interfaces.Entities;
global using Microsoft.EntityFrameworkCore;
global using RestSharp;
global using Serilog;
global using Serilog.Events;
global using Spectre.Console;
global using Spectre.Console.Cli;
global using Spectre.Console.Rendering;
global using DiscogsVideoDto = ParkSquare.Discogs.Dto.Video;
global using Log = CSharpScripts.Core.Log;
global using SearchResult = CSharpScripts.Models.SearchResult;
global using SpectreColor = Spectre.Console.Color;
global using SpectreProgress = Spectre.Console.Progress;
global using SpectreTable = Spectre.Console.Table;
