global using System.Collections.Frozen;
global using System.ComponentModel;
global using System.Diagnostics;
global using static System.Environment;
global using System.Globalization;
global using static System.IO.Directory;
global using static System.IO.File;
global using static System.IO.Path;
global using System.Net.Sockets;
global using static System.String;
global using System.Text.Encodings.Web;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Xml;
global using CSharpScripts.CLI.Commands;
global using CSharpScripts.Infrastructure;
global using CSharpScripts.Models;
global using CSharpScripts.Orchestrators;
global using CSharpScripts.Services.Mail;
global using CSharpScripts.Services.Music;
global using CSharpScripts.Services.Sync.Google;
global using CSharpScripts.Services.Sync.LastFm;
global using CSharpScripts.Services.Sync.YouTube;
global using CsvHelper;
global using CsvHelper.Configuration;
global using Google.Apis.Auth.OAuth2;
global using Google.Apis.Drive.v3;
global using Google.Apis.Services;
global using Google.Apis.Sheets.v4;
global using Google.Apis.Sheets.v4.Data;
global using Google.Apis.YouTube.v3.Data;
global using Hqub.Lastfm;
global using MetaBrainz.Common;
global using MetaBrainz.MusicBrainz;
global using MetaBrainz.MusicBrainz.Interfaces.Browses;
global using MetaBrainz.MusicBrainz.Interfaces.Entities;
global using MetaBrainz.MusicBrainz.Interfaces.Searches;
global using MetaBrainz.MusicBrainz.Objects;
global using ParkSquare.Discogs;
global using ParkSquare.Discogs.Dto;
global using Polly;
global using Polly.Retry;
global using RestSharp;
global using Spectre.Console;
global using Spectre.Console.Cli;
global using Spectre.Console.Rendering;
global using Console = CSharpScripts.Infrastructure.Console;
global using DiscogsVideoDto = ParkSquare.Discogs.Dto.Video;
global using Scrobble = CSharpScripts.Services.Sync.LastFm.Scrobble;
global using SearchResult = CSharpScripts.Models.SearchResult;
global using SpectreColor = Spectre.Console.Color;
global using SpectreProgress = Spectre.Console.Progress;
global using SpectreTable = Spectre.Console.Table;
global using YouTubeService = CSharpScripts.Services.Sync.YouTube.YouTubeService;
global using YouTubeServiceApi = Google.Apis.YouTube.v3.YouTubeService;
