<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<GenerateProgramFile>false</GenerateProgramFile>
		<UseMicrosoftTestingPlatform>true</UseMicrosoftTestingPlatform>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Classical\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="*" />
		<PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="*" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="*" />
		<PackageReference Include="TUnit" Version="*" />
		<PackageReference Include="Testcontainers.PostgreSql" Version="*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Scripts.csproj" />
	</ItemGroup>
</Project>
