// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scripts.Data;

#nullable disable

namespace Scripts.Migrations
{
    [DbContext(typeof(ScriptsDbContext))]
    partial class ScriptsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scripts.Data.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("idx_albums_release_date");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_albums_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ArtistId", "Title")
                        .IsUnique()
                        .HasDatabaseName("idx_albums_title");

                    b.ToTable("albums", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_artists_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("artists", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.ExecutionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_execution_logs_session_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_execution_logs_timestamp");

                    b.ToTable("execution_logs", (string)null);
                });

            modelBuilder.Entity("Scripts.Data.Entities.FailedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExecutionLogId")
                        .HasColumnType("integer");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionLogId")
                        .HasDatabaseName("idx_failed_tasks_execution_log_id");

                    b.HasIndex("TaskName")
                        .HasDatabaseName("idx_failed_tasks_task_name");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_failed_tasks_timestamp");

                    b.ToTable("failed_tasks", (string)null);
                });

            modelBuilder.Entity("Scripts.Data.Entities.FiberyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FiberyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<JsonDocument>("RawData")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("idx_fibery_entities_entity_type");

                    b.HasIndex("FiberyId", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("idx_fibery_entities_fibery_id_type");

                    b.ToTable("fibery_entities", "fibery");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("movements", "classical");
                });

            modelBuilder.Entity("Scripts.Data.Entities.MusicWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Composer")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("works", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.ReleaseProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Composer")
                        .HasColumnType("text");

                    b.Property<string>("Conductor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Orchestra")
                        .HasColumnType("text");

                    b.Property<string>("RecordingId")
                        .HasColumnType("text");

                    b.Property<string>("RecordingVenue")
                        .HasColumnType("text");

                    b.Property<int?>("RecordingYear")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Soloists")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer");

                    b.Property<string>("WorkName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_release_progress_created_at");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("idx_release_progress_release_id");

                    b.HasIndex("ReleaseId", "DiscNumber", "TrackNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_release_progress_track");

                    b.ToTable("release_progress", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Scrobble", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("ScrobbledAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Platform")
                        .HasDatabaseName("idx_scrobbles_platform");

                    b.HasIndex("ScrobbledAt")
                        .HasDatabaseName("idx_scrobbles_scrobbled_at");

                    b.HasIndex("TrackId");

                    b.HasIndex("Platform", "ScrobbledAt")
                        .HasDatabaseName("idx_scrobbles_platform_scrobbled_at");

                    b.HasIndex("TrackId", "ScrobbledAt")
                        .IsUnique()
                        .HasDatabaseName("idx_scrobbles_timestamp");

                    b.ToTable("scrobbles", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.SourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("RawData")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("idx_source_records_entity_type");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("idx_source_records_source_id");

                    b.HasIndex("SourceId", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("idx_source_records_source_entity_type");

                    b.ToTable("source_records", (string)null);
                });

            modelBuilder.Entity("Scripts.Data.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("MovementId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("MovementId");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_tracks_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("WorkId");

                    b.HasIndex("ArtistId", "Title")
                        .IsUnique()
                        .HasDatabaseName("idx_tracks_artist_title");

                    b.ToTable("tracks", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("SyncedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("UploadDate")
                        .HasColumnType("date");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName")
                        .HasDatabaseName("idx_videos_channel");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_videos_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UploadDate")
                        .HasDatabaseName("idx_videos_upload_date");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("idx_videos_url");

                    b.HasIndex("ChannelName", "UploadDate")
                        .HasDatabaseName("idx_videos_channel_upload_date");

                    b.ToTable("videos", "youtube");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Album", b =>
                {
                    b.HasOne("Scripts.Data.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Scripts.Data.Entities.FailedTask", b =>
                {
                    b.HasOne("Scripts.Data.Entities.ExecutionLog", "ExecutionLog")
                        .WithMany("FailedTasks")
                        .HasForeignKey("ExecutionLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExecutionLog");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Movement", b =>
                {
                    b.HasOne("Scripts.Data.Entities.MusicWork", "MusicWork")
                        .WithMany("Movements")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MusicWork");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Scrobble", b =>
                {
                    b.HasOne("Scripts.Data.Entities.Track", "Track")
                        .WithMany("Scrobbles")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Track", b =>
                {
                    b.HasOne("Scripts.Data.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Scripts.Data.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Scripts.Data.Entities.Movement", "Movement")
                        .WithMany("Tracks")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Scripts.Data.Entities.MusicWork", "MusicWork")
                        .WithMany("Tracks")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Album");

                    b.Navigation("Artist");

                    b.Navigation("Movement");

                    b.Navigation("MusicWork");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Scripts.Data.Entities.ExecutionLog", b =>
                {
                    b.Navigation("FailedTasks");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Movement", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Scripts.Data.Entities.MusicWork", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Track", b =>
                {
                    b.Navigation("Scrobbles");
                });
#pragma warning restore 612, 618
        }
    }
}
