// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scripts.Data;

#nullable disable

namespace Scripts.Migrations
{
    [DbContext(typeof(ScriptsDbContext))]
    partial class ScriptsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scripts.Data.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("idx_albums_release_date");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_albums_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ArtistId", "Title")
                        .IsUnique()
                        .HasDatabaseName("idx_albums_title");

                    b.ToTable("albums", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_artists_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("artists", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.FiberyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FiberyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<JsonDocument>("RawData")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("idx_fibery_entities_entity_type");

                    b.HasIndex("FiberyId", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("idx_fibery_entities_fibery_id_type");

                    b.ToTable("fibery_entities", "fibery");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelNameLower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleLower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId")
                        .IsUnique();

                    b.ToTable("playlists", "youtube");
                });

            modelBuilder.Entity("Scripts.Data.Entities.PlaylistVideo", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("playlist_videos", "youtube");
                });

            modelBuilder.Entity("Scripts.Data.Entities.ReleaseProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Composer")
                        .HasColumnType("text");

                    b.Property<string>("Conductor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Orchestra")
                        .HasColumnType("text");

                    b.Property<string>("RecordingId")
                        .HasColumnType("text");

                    b.Property<string>("RecordingVenue")
                        .HasColumnType("text");

                    b.Property<int?>("RecordingYear")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Soloists")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer");

                    b.Property<string>("WorkName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_release_progress_created_at");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("idx_release_progress_release_id");

                    b.HasIndex("ReleaseId", "DiscNumber", "TrackNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_release_progress_track");

                    b.ToTable("release_progress", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Scrobble", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("ScrobbledAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Platform")
                        .HasDatabaseName("idx_scrobbles_platform");

                    b.HasIndex("ScrobbledAt")
                        .HasDatabaseName("idx_scrobbles_scrobbled_at");

                    b.HasIndex("TrackId");

                    b.HasIndex("Platform", "ScrobbledAt")
                        .HasDatabaseName("idx_scrobbles_platform_scrobbled_at");

                    b.HasIndex("TrackId", "ScrobbledAt")
                        .IsUnique()
                        .HasDatabaseName("idx_scrobbles_timestamp");

                    b.ToTable("scrobbles", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.SourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("RawData")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("idx_source_records_entity_type");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("idx_source_records_source_id");

                    b.HasIndex("SourceId", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("idx_source_records_source_entity_type");

                    b.ToTable("source_records", (string)null);
                });

            modelBuilder.Entity("Scripts.Data.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_tracks_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ArtistId", "Title")
                        .IsUnique()
                        .HasDatabaseName("idx_tracks_artist_title");

                    b.ToTable("tracks", "music");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelNameLower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleLower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("text");

                    b.Property<string>("TranslatedTitle")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("UploadDate")
                        .HasColumnType("date");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("videos", "youtube");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Album", b =>
                {
                    b.HasOne("Scripts.Data.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Scripts.Data.Entities.PlaylistVideo", b =>
                {
                    b.HasOne("Scripts.Data.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistVideos")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scripts.Data.Entities.Video", "Video")
                        .WithMany("PlaylistVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Scrobble", b =>
                {
                    b.HasOne("Scripts.Data.Entities.Track", "Track")
                        .WithMany("Scrobbles")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Track", b =>
                {
                    b.HasOne("Scripts.Data.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Scripts.Data.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistVideos");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Track", b =>
                {
                    b.Navigation("Scrobbles");
                });

            modelBuilder.Entity("Scripts.Data.Entities.Video", b =>
                {
                    b.Navigation("PlaylistVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
