// <auto-generated />
using CSharpScripts.Data;
using CSharpScripts.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ScriptsDbContext), typeof(ScriptsDbContextModel))]
