// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CSharpScripts.Data.CompiledModels
{
    public partial class ScriptsDbContextModel
    {
        private ScriptsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("384de18c-1857-438b-9dac-0cd9a4bc9f48"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var album = AlbumEntityType.Create(this);
            var artist = ArtistEntityType.Create(this);
            var executionLog = ExecutionLogEntityType.Create(this);
            var failedTask = FailedTaskEntityType.Create(this);
            var fiberyEntity = FiberyEntityEntityType.Create(this);
            var scrobble = ScrobbleEntityType.Create(this);
            var sourceRecord = SourceRecordEntityType.Create(this);
            var track = TrackEntityType.Create(this);
            var video = VideoEntityType.Create(this);

            AlbumEntityType.CreateForeignKey1(album, artist);
            ScrobbleEntityType.CreateForeignKey1(scrobble, track);
            TrackEntityType.CreateForeignKey1(track, album);
            TrackEntityType.CreateForeignKey2(track, artist);

            AlbumEntityType.CreateAnnotations(album);
            ArtistEntityType.CreateAnnotations(artist);
            ExecutionLogEntityType.CreateAnnotations(executionLog);
            FailedTaskEntityType.CreateAnnotations(failedTask);
            FiberyEntityEntityType.CreateAnnotations(fiberyEntity);
            ScrobbleEntityType.CreateAnnotations(scrobble);
            SourceRecordEntityType.CreateAnnotations(sourceRecord);
            TrackEntityType.CreateAnnotations(track);
            VideoEntityType.CreateAnnotations(video);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
